Repository Puzzlepart/prosjektportalen, pull requests merged in 2020-11, with the labels that each got.

#770 Added ProjectStats highcharts styling
  src/css/components/ProjectStats.styl
Labels: bug

#775 Problem creating diagrams
  CHANGELOG.md
  src/js/WebParts/ProjectStats/IProjectStatsProps.ts
  src/js/WebParts/ProjectStats/index.tsx
Labels: Complexity: small, backend, bug

#777 Added ability to hide list and RiskShowPostAction in RiskMatrix webpart
  CHANGELOG.md
  src/js/WebParts/RiskMatrix/IRiskMatrixProps.ts
  src/js/WebParts/RiskMatrix/index.tsx
Labels: frontend
